### PR TITLE
fix heading definition

### PR DESCRIPTION
**Pull request by mcfogarty**

### CODE REVIEW

**Comment by mcfogarty** [comment]
Be sure to update the documentation to give better definitions of pitch, roll, and heading. Heading should be direction of x axis relative to north, positive clockwise. Pitch is positive when z is up and x pitches up. Roll follows right hand rule.

**Comment by mcfogarty** [comment]
Output for heading is currently -180 to +180. Suggest changing it to 0-360 and making this consistent throughout DOLfYN.

**Comment by mcfogarty** [comment]
Re: previous comment, I edited the function to provide heading in range 0-360

**Comment by lkilcher** [comment]
Closing this in favor of #50.

**Pull request closed without merging**
