### PR TITLE
Copy `raw_ds.attrs` to `out_ds.attrs`

### PR DESCRIPTION
**Pull request by lkilcher**
The `VelBinner.do_{var, avg}` methods weren't previously copying attributes. I think this was an oversight?

Also- the second commit makes sure we that the tests compare attrs. However: I have not updated the test files, so the tests currently fail.

### CODE REVIEW

**Comment by jmcvey3** [comment]
> The `VelBinner.do_{var, avg}` methods weren't previously copying attributes. I think this was an oversight?
> 
> Also- the second commit makes sure we that the tests compare attrs. However: I have not updated the test files, so the tests currently fail.

Ohhh, good catch

**Comment by lkilcher** [comment]
OK, this is rebased on master now. I'm hoping @jmcvey3 can fix the test-data files to include the copied `attrs`. It looks like this is where *all* of the failures are at the moment. A couple more details that I'm noticing here:
- Some of the failures are errors on comparing arrays in attrs (i.e., `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`). So you may need to update the `tests.base.assert_allclose` function to manage that.
- The `test_do_rdi` test is spitting out A LOT of text to stdout. Is this intentional (e.g., due to running a test with some debug level), or an artifact of some unnecessary `print` statements?

**Comment by lkilcher** [comment]
@jmcvey3 - Another thought: if the stdout from test_do_rdi is a part of testing the debug code, should we be validating that what stdout outputs is consistent. On the one hand ensuring that this output is stable may not be critical (i.e., to the API), but on the other as a 'testing best practice' it probably makes sense to *actually test* the debug output rather than *just running it* in order to boost coverage.

**Comment by lkilcher** [comment]
You should be able to accomplish this using [`contextlib.redirect_stdout`](https://docs.python.org/3.5/library/contextlib.html#contextlib.redirect_stdout).

**Comment by jmcvey3** [comment]
> You should be able to accomplish this using [`contextlib.redirect_stdout`](https://docs.python.org/3.5/library/contextlib.html#contextlib.redirect_stdout).

Much thanks, I'll add that.

**Comment by jmcvey3** [comment]
@lkilcher Ended up rebuilding all the test data. All of the timestamps shifted down by less than 1 microsecond for some reason

**Comment by lkilcher** [comment]
I see two possible solutions here:
1. Modify the filecmp step inside the tests to ignore path differences.
2. Modify the print statements inside the functions so that they don't give absolute path names.

I think option 1 is preferred, because I think it's nice for those print statements to say exactly which file you're working on, but I could live with 2. ... Since it's probably easier. 

... On a sidenote: my mind is a bit blown right now as to why some of these tests are passing and others are failing.

**Comment by jmcvey3** [comment]
> I see two possible solutions here:
> 
> 1. Modify the filecmp step inside the tests to ignore path differences.
> 2. Modify the print statements inside the functions so that they don't give absolute path names.
> 
> I think option 1 is preferred, because I think it's nice for those print statements to say exactly which file you're working on, but I could live with 2. ... Since it's probably easier.
> 
> ... On a sidenote: my mind is a bit blown right now as to why some of these tests are passing and others are failing.

Went with option 1.

**Pull request merged**
