### PR TITLE
TRDI reader updates

### PR DESCRIPTION
**Pull request by jmcvey3**
Large update that includes bugfixes for reading VMDAS datafiles (subsuming fixes from PR #92), the ability to read NMEA string data (and bugfixes to skip bad profiles) stored from Winriver2, and small structure updates given the latest PDDecoder SDK released by TRDI. Full changes are listed in the changelog.

### CODE REVIEW

**Comment by jmcvey3** [comment]
@jklymak can you please provide a sample of VMDAS data (from #92, with the misplaced navigation header and/or interleaved nb and bb pings ) so I can add it to the test data suite and finish this pull request?

**Comment by jmcvey3** [comment]
@jklymak Pinging you again if you can upload a clip of VMDAS test data

**Comment by jklymak** [comment]
My sincere apologies for being so slow in responding to your request.  

https://ocean-physics.seos.uvic.ca/~jklymak/ExampleADCP/

has some files that I believe are inter-leaved ADCP data.  Part of my slowness was not being sure what was in each file.  If those don't suit, I can make the whole dataset available.  I actually ended up making more modifications to get these to read cleanly, but perhaps you have managed those yourselves.  

Thanks!

**Comment by jmcvey3** [comment]
No worries at all, bad timing on my part on when to close this PR.

To just get this to run through dolfyn, I only needed to add a line to skip 48 bytes for id # 12504, (hex 30D8). I couldn't find documentation to decode id's 12504 and 12288 though, but I'm not very familiar with ocean surveyors.

**Pull request merged**
