### PR TITLE
Crop tools

### PR DESCRIPTION
**Pull request by lillieogden**
Creating a crop tools branch and adding tools.py to dolfyn.adv

### CODE REVIEW

**Comment by lkilcher** [comment]
@lillieogden I'm not really sure how this happened, but this is still the wrong branch. There should only be one (or two) commits and one file changed, not 154 and 31. Why don't you delete this branch (from your local repo, [AND github](https://help.github.com/articles/viewing-branches-in-your-repository/)), then do this:

    git checkout master
    git checkout -b 'crop_tools2'

Then add your files. Then do:

    git push -u origin crop_tools2

I suspect that you either: a) did not delete the branch on github, or b) did not do the first git command above when you created a new branch (i.e. you've got to be on the branch you want to branch from when you create a new one with `git checkout -b`).

**Comment by lkilcher** [comment]
Then create a new PR that points to `crop_tools2`.

**Comment by lillieogden** [comment]
@lkilcher I am not sure how this happened but my master branch is back to being 30 commits behind you. I tried the following code
`git fetch upstream`
`git merge upstream/master --ff-only`
`git reset --hard upstream/master`
but it didn't work. Is it possible that the pull request I sent you included those changes to the master branch in addition to the new branch and that was why there were so many commits? Either way, I am at home trying to trouble shoot this and read about mpld3.

**Comment by lkilcher** [comment]
Check to make sure that you are on `master` when you run that last command. Also, check to confirm that `upstream` points to my repository (`origin` should point to yours).

**Comment by lkilcher** [comment]
Also, I don't think you need the `merge` command.

**Pull request closed without merging**
